### ISSUE TITLE
eruda 实例被重复创建

### ISSUE THREAD

**Issue by Airkro** [huruji/eruda-webpack-plugin#3]
对于使用了多个 entry 或者 split chunks 的项目，eruda 实例被重复创建。经检测，每一个脚本都被插入 eruda 代码。

![image](https://user-images.githubusercontent.com/12206891/54013159-1f348d80-41b3-11e9-90dc-a49ddce58f6b.png)

**Comment by huruji** [comment]
是的，这是一个已知的问题，这两天我会看一下已解决这个问题，感谢反馈

**Comment by huruji** [comment]
@Airkro

**Comment by huruji** [comment]
fixed, see [1.2.0](https://github.com/huruji/eruda-webpack-plugin/commit/b99d87967db967181bb085df338eaea8093d6e88)

文档： [README](https://github.com/huruji/eruda-webpack-plugin/blob/master/README_CN.md)

**Comment by huruji** [comment]
@Airkro
